---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vllm
spec:
  replicas: 8
  selector:
    matchLabels:
      app: vllm
  template:
    metadata:
      labels:
        app: vllm
    spec:
      containers:
      - command: [ "/bin/sh", "-c" ]
        args: [ "pip3 install --upgrade transformers; vllm serve unsloth/Llama-3.1-8B-Instruct" ]
        env:
        - name: HF_TOKEN
          valueFrom:
            secretKeyRef:
              name: hf-secret
              key: hf_token
        - name: HF_USERNAME
          valueFrom:
            secretKeyRef:
              name: hf-secret
              key: hf_username
        image: vllm/vllm-openai:v0.8.5
        name: inference-server
        resources:
          limits:
            cpu: '16'
            memory: 180Gi
            nvidia.com/gpu: '1'
          requests:
            cpu: '16'
            memory: 180Gi
            nvidia.com/gpu: '1'
        volumeMounts:
        - mountPath: /dev/shm
          name: dshm
      tolerations:
      - effect: NoSchedule
        key: nvidia.com/gpu
        operator: Equal
        value: present
      nodeSelector:
        cloud.google.com/gke-accelerator: nvidia-h100-80gb
        cloud.google.com/gke-spot: "true"
      volumes:
      - name: dshm
        emptyDir:
          medium: Memory
---
apiVersion: v1
kind: Service
metadata:
  name: vllm-endpoint
spec:
  selector:
    app: vllm
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000

