---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vllm
spec:
  replicas: 8
  selector:
    matchLabels:
      app: vllm
  template:
    metadata:
      labels:
        app: vllm
      annotations:
        gke-gcsfuse/volumes: "true"
    spec:
      serviceAccountName: bucket-sa
      containers:
        #- command: [ "/bin/sh", "-c", "sleep 6000" ]
      - command: [ "/bin/sh", "-c" ]
        args: [ "pip3 install vllm[runai]; vllm serve /data/Llama-3.1-8B-Instruct/ --served-model-name llama --load-format runai_streamer --dtype=bfloat16" ]
        env:
        - name: RUNAI_STREAMER_CONCURRENCY
          value: "24"
        image: vllm/vllm-openai:v0.7.3
          #image: google/cloud-sdk 
        name: inference-server
        resources:
          limits:
            cpu: '16'
            memory: 180Gi
            nvidia.com/gpu: '1'
          requests:
            cpu: '16'
            memory: 180Gi
            nvidia.com/gpu: '1'
        volumeMounts:
        - mountPath: /dev/shm
          name: dshm
        - name: gcs-fuse-csi-ephemeral
          mountPath: /data
          readOnly: true
      tolerations:
      - effect: NoSchedule
        key: nvidia.com/gpu
        operator: Equal
        value: present
      nodeSelector:
        cloud.google.com/gke-accelerator: nvidia-h100-80gb
          #cloud.google.com/gke-accelerator-count: "8"
          #cloud.google.com/gke-gpu-driver-version: latest
        cloud.google.com/gke-spot: "true"
      volumes:
      - name: dshm
        emptyDir:
          medium: Memory
      - name: gcs-fuse-csi-ephemeral
        csi:
          driver: gcsfuse.csi.storage.gke.io
          readOnly: true
          volumeAttributes:
            bucketName: epam-team-gpu-benchmark
            mountOptions: "implicit-dirs,metadata-cache:ttl-secs:-1,file-cache:max-size-mb:-1,file-cache:cache-file-for-range-read:false,file-cache:enable-parallel-downloads:true,file-cache:download-chunk-size-mb:32,metadata-cache:stat-cache-max-size-mb:32,metadata-cache:ttl-secs:3600,metadata-cache:type-cache-max-size-mb:4"
---
apiVersion: v1
kind: Service
metadata:
  name: vllm-endpoint
spec:
  selector:
    app: vllm
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000

