---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: benchmark
spec:
  replicas: 1
  selector:
    matchLabels:
      app: benchmark
  template:
    metadata:
      labels:
        app: benchmark
    spec:
      containers:
      - command: [ "/bin/sh", "-c", "sleep 36000" ]
        #- command: [ "/bin/sh", "-c" ]
        #args: [ "pip3 install vllm[runai]; vllm serve /data/Llama-3.1-8B-Instruct/ --served-model-name llama --load-format runai_streamer --dtype=bfloat16" ]
        image: dganochenko/inference-benchmark:0.0.1
          #image: google/cloud-sdk 
        name: benchmark
        env:
        - name: HF_TOKEN
          valueFrom:
            secretKeyRef:
              name: hf-secret
              key: hf_token
        - name: HF_USERNAME
          valueFrom:
            secretKeyRef:
              name: hf-secret
              key: hf_username
        resources:
          limits:
            cpu: '2'
            memory: 8Gi
          requests:
            cpu: '1'
            memory: 8Gi
      nodeSelector:
        eks.amazonaws.com/compute-type: auto
      tolerations:
      - effect: NoSchedule
        key: nvidia.com/gpu
        operator: Equal
        value: present

