---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: benchmark
spec:
  replicas: 1
  selector:
    matchLabels:
      app: benchmark
  template:
    metadata:
      labels:
        app: benchmark
    spec:
      containers:
      - command: [ "/bin/sh", "-c", "sleep 36000" ]
        #- command: [ "/bin/sh", "-c" ]
        #args: [ "pip3 install vllm[runai]; vllm serve /data/Llama-3.1-8B-Instruct/ --served-model-name llama --load-format runai_streamer --dtype=bfloat16" ]
        image: dganochenko/inference-benchmark:0.0.1
          #image: google/cloud-sdk 
        name: benchmark
        resources:
          limits:
            cpu: '1'
            memory: 8Gi
          requests:
            cpu: '2'
            memory: 8Gi

